services:
  backend:
    image: plone/plone-backend:6.0
    ports:
      - "8080:8080"
    environment:
      SITE: Plone
  frontend:
    image: plone/plone-frontend
    ports:
      - "3000:3000"
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      RAZZLE_API_PATH: http://localhost:8080/Plone
    depends_on:
      - backend
